// @generated by scripts/sync_from_snowball.py — DO NOT EDIT

#[cfg(feature = "arabic")]
pub mod arabic_stemmer;

#[cfg(feature = "armenian")]
pub mod armenian_stemmer;

#[cfg(feature = "basque")]
pub mod basque_stemmer;

#[cfg(feature = "catalan")]
pub mod catalan_stemmer;

#[cfg(feature = "czech")]
pub mod czech_stemmer;

#[cfg(feature = "danish")]
pub mod danish_stemmer;

#[cfg(feature = "dutch")]
pub mod dutch_stemmer;

#[cfg(feature = "dutch_porter")]
pub mod dutch_porter_stemmer;

#[cfg(feature = "earlymodernenglish")]
pub mod earlymodernenglish_stemmer;

#[cfg(feature = "english")]
pub mod english_stemmer;

#[cfg(feature = "esperanto")]
pub mod esperanto_stemmer;

#[cfg(feature = "estonian")]
pub mod estonian_stemmer;

#[cfg(feature = "finnish")]
pub mod finnish_stemmer;

#[cfg(feature = "french")]
pub mod french_stemmer;

#[cfg(feature = "german")]
pub mod german_stemmer;

#[cfg(feature = "greek")]
pub mod greek_stemmer;

#[cfg(feature = "hindi")]
pub mod hindi_stemmer;

#[cfg(feature = "hungarian")]
pub mod hungarian_stemmer;

#[cfg(feature = "indonesian")]
pub mod indonesian_stemmer;

#[cfg(feature = "irish")]
pub mod irish_stemmer;

#[cfg(feature = "italian")]
pub mod italian_stemmer;

#[cfg(feature = "lithuanian")]
pub mod lithuanian_stemmer;

#[cfg(feature = "lovins")]
pub mod lovins_stemmer;

#[cfg(feature = "nepali")]
pub mod nepali_stemmer;

#[cfg(feature = "norwegian")]
pub mod norwegian_stemmer;

#[cfg(feature = "persian")]
pub mod persian_stemmer;

#[cfg(feature = "polish")]
pub mod polish_stemmer;

#[cfg(feature = "porter")]
pub mod porter_stemmer;

#[cfg(feature = "portuguese")]
pub mod portuguese_stemmer;

#[cfg(feature = "romanian")]
pub mod romanian_stemmer;

#[cfg(feature = "russian")]
pub mod russian_stemmer;

#[cfg(feature = "serbian")]
pub mod serbian_stemmer;

#[cfg(feature = "sesotho")]
pub mod sesotho_stemmer;

#[cfg(feature = "spanish")]
pub mod spanish_stemmer;

#[cfg(feature = "swedish")]
pub mod swedish_stemmer;

#[cfg(feature = "tamil")]
pub mod tamil_stemmer;

#[cfg(feature = "turkish")]
pub mod turkish_stemmer;

#[cfg(feature = "yiddish")]
pub mod yiddish_stemmer;
