// @generated by scripts/sync_from_snowball.py — DO NOT EDIT

/// Snowball stemming algorithm.
///
/// Variants are gated by Cargo features of the same snake_case name.
/// The enum is `#[non_exhaustive]` so new upstream algorithms are not a
/// major-version break for downstream `match` expressions that keep a
/// wildcard arm.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum Algorithm {
    #[cfg(feature = "arabic")]
    Arabic,
    #[cfg(feature = "armenian")]
    Armenian,
    #[cfg(feature = "basque")]
    Basque,
    #[cfg(feature = "catalan")]
    Catalan,
    #[cfg(feature = "czech")]
    Czech,
    #[cfg(feature = "danish")]
    Danish,
    #[cfg(feature = "dutch")]
    Dutch,
    #[cfg(feature = "dutch_porter")]
    DutchPorter,
    #[cfg(feature = "earlymodernenglish")]
    Earlymodernenglish,
    #[cfg(feature = "english")]
    English,
    #[cfg(feature = "esperanto")]
    Esperanto,
    #[cfg(feature = "estonian")]
    Estonian,
    #[cfg(feature = "finnish")]
    Finnish,
    #[cfg(feature = "french")]
    French,
    #[cfg(feature = "german")]
    German,
    #[cfg(feature = "greek")]
    Greek,
    #[cfg(feature = "hindi")]
    Hindi,
    #[cfg(feature = "hungarian")]
    Hungarian,
    #[cfg(feature = "indonesian")]
    Indonesian,
    #[cfg(feature = "irish")]
    Irish,
    #[cfg(feature = "italian")]
    Italian,
    #[cfg(feature = "lithuanian")]
    Lithuanian,
    #[cfg(feature = "lovins")]
    Lovins,
    #[cfg(feature = "nepali")]
    Nepali,
    #[cfg(feature = "norwegian")]
    Norwegian,
    #[cfg(feature = "persian")]
    Persian,
    #[cfg(feature = "polish")]
    Polish,
    #[cfg(feature = "porter")]
    Porter,
    #[cfg(feature = "portuguese")]
    Portuguese,
    #[cfg(feature = "romanian")]
    Romanian,
    #[cfg(feature = "russian")]
    Russian,
    #[cfg(feature = "serbian")]
    Serbian,
    #[cfg(feature = "sesotho")]
    Sesotho,
    #[cfg(feature = "spanish")]
    Spanish,
    #[cfg(feature = "swedish")]
    Swedish,
    #[cfg(feature = "tamil")]
    Tamil,
    #[cfg(feature = "turkish")]
    Turkish,
    #[cfg(feature = "yiddish")]
    Yiddish,
}

impl Algorithm {
    /// Canonical Snowball algorithm id (feature name).
    pub const fn name(self) -> &'static str {
        match self {
            #[cfg(feature = "arabic")]
            Self::Arabic => "arabic",
            #[cfg(feature = "armenian")]
            Self::Armenian => "armenian",
            #[cfg(feature = "basque")]
            Self::Basque => "basque",
            #[cfg(feature = "catalan")]
            Self::Catalan => "catalan",
            #[cfg(feature = "czech")]
            Self::Czech => "czech",
            #[cfg(feature = "danish")]
            Self::Danish => "danish",
            #[cfg(feature = "dutch")]
            Self::Dutch => "dutch",
            #[cfg(feature = "dutch_porter")]
            Self::DutchPorter => "dutch_porter",
            #[cfg(feature = "earlymodernenglish")]
            Self::Earlymodernenglish => "earlymodernenglish",
            #[cfg(feature = "english")]
            Self::English => "english",
            #[cfg(feature = "esperanto")]
            Self::Esperanto => "esperanto",
            #[cfg(feature = "estonian")]
            Self::Estonian => "estonian",
            #[cfg(feature = "finnish")]
            Self::Finnish => "finnish",
            #[cfg(feature = "french")]
            Self::French => "french",
            #[cfg(feature = "german")]
            Self::German => "german",
            #[cfg(feature = "greek")]
            Self::Greek => "greek",
            #[cfg(feature = "hindi")]
            Self::Hindi => "hindi",
            #[cfg(feature = "hungarian")]
            Self::Hungarian => "hungarian",
            #[cfg(feature = "indonesian")]
            Self::Indonesian => "indonesian",
            #[cfg(feature = "irish")]
            Self::Irish => "irish",
            #[cfg(feature = "italian")]
            Self::Italian => "italian",
            #[cfg(feature = "lithuanian")]
            Self::Lithuanian => "lithuanian",
            #[cfg(feature = "lovins")]
            Self::Lovins => "lovins",
            #[cfg(feature = "nepali")]
            Self::Nepali => "nepali",
            #[cfg(feature = "norwegian")]
            Self::Norwegian => "norwegian",
            #[cfg(feature = "persian")]
            Self::Persian => "persian",
            #[cfg(feature = "polish")]
            Self::Polish => "polish",
            #[cfg(feature = "porter")]
            Self::Porter => "porter",
            #[cfg(feature = "portuguese")]
            Self::Portuguese => "portuguese",
            #[cfg(feature = "romanian")]
            Self::Romanian => "romanian",
            #[cfg(feature = "russian")]
            Self::Russian => "russian",
            #[cfg(feature = "serbian")]
            Self::Serbian => "serbian",
            #[cfg(feature = "sesotho")]
            Self::Sesotho => "sesotho",
            #[cfg(feature = "spanish")]
            Self::Spanish => "spanish",
            #[cfg(feature = "swedish")]
            Self::Swedish => "swedish",
            #[cfg(feature = "tamil")]
            Self::Tamil => "tamil",
            #[cfg(feature = "turkish")]
            Self::Turkish => "turkish",
            #[cfg(feature = "yiddish")]
            Self::Yiddish => "yiddish",
        }
    }

    /// All algorithms enabled in this build, in stable name order.
    pub fn all() -> &'static [Algorithm] {
        &[
            #[cfg(feature = "arabic")]
            Self::Arabic,
            #[cfg(feature = "armenian")]
            Self::Armenian,
            #[cfg(feature = "basque")]
            Self::Basque,
            #[cfg(feature = "catalan")]
            Self::Catalan,
            #[cfg(feature = "czech")]
            Self::Czech,
            #[cfg(feature = "danish")]
            Self::Danish,
            #[cfg(feature = "dutch")]
            Self::Dutch,
            #[cfg(feature = "dutch_porter")]
            Self::DutchPorter,
            #[cfg(feature = "earlymodernenglish")]
            Self::Earlymodernenglish,
            #[cfg(feature = "english")]
            Self::English,
            #[cfg(feature = "esperanto")]
            Self::Esperanto,
            #[cfg(feature = "estonian")]
            Self::Estonian,
            #[cfg(feature = "finnish")]
            Self::Finnish,
            #[cfg(feature = "french")]
            Self::French,
            #[cfg(feature = "german")]
            Self::German,
            #[cfg(feature = "greek")]
            Self::Greek,
            #[cfg(feature = "hindi")]
            Self::Hindi,
            #[cfg(feature = "hungarian")]
            Self::Hungarian,
            #[cfg(feature = "indonesian")]
            Self::Indonesian,
            #[cfg(feature = "irish")]
            Self::Irish,
            #[cfg(feature = "italian")]
            Self::Italian,
            #[cfg(feature = "lithuanian")]
            Self::Lithuanian,
            #[cfg(feature = "lovins")]
            Self::Lovins,
            #[cfg(feature = "nepali")]
            Self::Nepali,
            #[cfg(feature = "norwegian")]
            Self::Norwegian,
            #[cfg(feature = "persian")]
            Self::Persian,
            #[cfg(feature = "polish")]
            Self::Polish,
            #[cfg(feature = "porter")]
            Self::Porter,
            #[cfg(feature = "portuguese")]
            Self::Portuguese,
            #[cfg(feature = "romanian")]
            Self::Romanian,
            #[cfg(feature = "russian")]
            Self::Russian,
            #[cfg(feature = "serbian")]
            Self::Serbian,
            #[cfg(feature = "sesotho")]
            Self::Sesotho,
            #[cfg(feature = "spanish")]
            Self::Spanish,
            #[cfg(feature = "swedish")]
            Self::Swedish,
            #[cfg(feature = "tamil")]
            Self::Tamil,
            #[cfg(feature = "turkish")]
            Self::Turkish,
            #[cfg(feature = "yiddish")]
            Self::Yiddish,
        ]
    }

    /// Look up an algorithm by name or common alias (case-insensitive).
    pub fn from_name(name: &str) -> Result<Self, crate::error::UnknownAlgorithm> {
        let key = name.trim();
        let lower = key.to_ascii_lowercase();
        match lower.as_str() {
            #[cfg(feature = "arabic")]
            "ar" => Ok(Self::Arabic),
            #[cfg(feature = "arabic")]
            "ara" => Ok(Self::Arabic),
            #[cfg(feature = "arabic")]
            "arabic" => Ok(Self::Arabic),
            #[cfg(feature = "armenian")]
            "arm" => Ok(Self::Armenian),
            #[cfg(feature = "armenian")]
            "armenian" => Ok(Self::Armenian),
            #[cfg(feature = "basque")]
            "baq" => Ok(Self::Basque),
            #[cfg(feature = "basque")]
            "basque" => Ok(Self::Basque),
            #[cfg(feature = "catalan")]
            "ca" => Ok(Self::Catalan),
            #[cfg(feature = "catalan")]
            "cat" => Ok(Self::Catalan),
            #[cfg(feature = "catalan")]
            "catalan" => Ok(Self::Catalan),
            #[cfg(feature = "czech")]
            "ces" => Ok(Self::Czech),
            #[cfg(feature = "czech")]
            "cs" => Ok(Self::Czech),
            #[cfg(feature = "czech")]
            "cze" => Ok(Self::Czech),
            #[cfg(feature = "czech")]
            "czech" => Ok(Self::Czech),
            #[cfg(feature = "danish")]
            "da" => Ok(Self::Danish),
            #[cfg(feature = "danish")]
            "dan" => Ok(Self::Danish),
            #[cfg(feature = "danish")]
            "danish" => Ok(Self::Danish),
            #[cfg(feature = "german")]
            "de" => Ok(Self::German),
            #[cfg(feature = "german")]
            "deu" => Ok(Self::German),
            #[cfg(feature = "dutch")]
            "dut" => Ok(Self::Dutch),
            #[cfg(feature = "dutch")]
            "dutch" => Ok(Self::Dutch),
            #[cfg(feature = "dutch_porter")]
            "dutch_porter" => Ok(Self::DutchPorter),
            #[cfg(feature = "earlymodernenglish")]
            "earlymodernenglish" => Ok(Self::Earlymodernenglish),
            #[cfg(feature = "greek")]
            "el" => Ok(Self::Greek),
            #[cfg(feature = "greek")]
            "ell" => Ok(Self::Greek),
            #[cfg(feature = "english")]
            "en" => Ok(Self::English),
            #[cfg(feature = "english")]
            "eng" => Ok(Self::English),
            #[cfg(feature = "english")]
            "english" => Ok(Self::English),
            #[cfg(feature = "esperanto")]
            "eo" => Ok(Self::Esperanto),
            #[cfg(feature = "esperanto")]
            "epo" => Ok(Self::Esperanto),
            #[cfg(feature = "spanish")]
            "es" => Ok(Self::Spanish),
            #[cfg(feature = "spanish")]
            "esl" => Ok(Self::Spanish),
            #[cfg(feature = "esperanto")]
            "esperanto" => Ok(Self::Esperanto),
            #[cfg(feature = "estonian")]
            "est" => Ok(Self::Estonian),
            #[cfg(feature = "estonian")]
            "estonian" => Ok(Self::Estonian),
            #[cfg(feature = "estonian")]
            "et" => Ok(Self::Estonian),
            #[cfg(feature = "basque")]
            "eu" => Ok(Self::Basque),
            #[cfg(feature = "basque")]
            "eus" => Ok(Self::Basque),
            #[cfg(feature = "persian")]
            "fa" => Ok(Self::Persian),
            #[cfg(feature = "persian")]
            "fas" => Ok(Self::Persian),
            #[cfg(feature = "finnish")]
            "fi" => Ok(Self::Finnish),
            #[cfg(feature = "finnish")]
            "fin" => Ok(Self::Finnish),
            #[cfg(feature = "finnish")]
            "finnish" => Ok(Self::Finnish),
            #[cfg(feature = "french")]
            "fr" => Ok(Self::French),
            #[cfg(feature = "french")]
            "fra" => Ok(Self::French),
            #[cfg(feature = "french")]
            "fre" => Ok(Self::French),
            #[cfg(feature = "french")]
            "french" => Ok(Self::French),
            #[cfg(feature = "irish")]
            "ga" => Ok(Self::Irish),
            #[cfg(feature = "german")]
            "ger" => Ok(Self::German),
            #[cfg(feature = "german")]
            "german" => Ok(Self::German),
            #[cfg(feature = "irish")]
            "gle" => Ok(Self::Irish),
            #[cfg(feature = "greek")]
            "gre" => Ok(Self::Greek),
            #[cfg(feature = "greek")]
            "greek" => Ok(Self::Greek),
            #[cfg(feature = "hindi")]
            "hi" => Ok(Self::Hindi),
            #[cfg(feature = "hindi")]
            "hin" => Ok(Self::Hindi),
            #[cfg(feature = "hindi")]
            "hindi" => Ok(Self::Hindi),
            #[cfg(feature = "hungarian")]
            "hu" => Ok(Self::Hungarian),
            #[cfg(feature = "hungarian")]
            "hun" => Ok(Self::Hungarian),
            #[cfg(feature = "hungarian")]
            "hungarian" => Ok(Self::Hungarian),
            #[cfg(feature = "armenian")]
            "hy" => Ok(Self::Armenian),
            #[cfg(feature = "armenian")]
            "hye" => Ok(Self::Armenian),
            #[cfg(feature = "indonesian")]
            "id" => Ok(Self::Indonesian),
            #[cfg(feature = "indonesian")]
            "ind" => Ok(Self::Indonesian),
            #[cfg(feature = "indonesian")]
            "indonesian" => Ok(Self::Indonesian),
            #[cfg(feature = "irish")]
            "irish" => Ok(Self::Irish),
            #[cfg(feature = "italian")]
            "it" => Ok(Self::Italian),
            #[cfg(feature = "italian")]
            "ita" => Ok(Self::Italian),
            #[cfg(feature = "italian")]
            "italian" => Ok(Self::Italian),
            #[cfg(feature = "dutch")]
            "kraaij_pohlmann" => Ok(Self::Dutch),
            #[cfg(feature = "lithuanian")]
            "lit" => Ok(Self::Lithuanian),
            #[cfg(feature = "lithuanian")]
            "lithuanian" => Ok(Self::Lithuanian),
            #[cfg(feature = "lovins")]
            "lovins" => Ok(Self::Lovins),
            #[cfg(feature = "lithuanian")]
            "lt" => Ok(Self::Lithuanian),
            #[cfg(feature = "nepali")]
            "ne" => Ok(Self::Nepali),
            #[cfg(feature = "nepali")]
            "nep" => Ok(Self::Nepali),
            #[cfg(feature = "nepali")]
            "nepali" => Ok(Self::Nepali),
            #[cfg(feature = "dutch")]
            "nl" => Ok(Self::Dutch),
            #[cfg(feature = "dutch")]
            "nld" => Ok(Self::Dutch),
            #[cfg(feature = "norwegian")]
            "no" => Ok(Self::Norwegian),
            #[cfg(feature = "norwegian")]
            "nor" => Ok(Self::Norwegian),
            #[cfg(feature = "norwegian")]
            "norwegian" => Ok(Self::Norwegian),
            #[cfg(feature = "persian")]
            "pers" => Ok(Self::Persian),
            #[cfg(feature = "persian")]
            "persian" => Ok(Self::Persian),
            #[cfg(feature = "polish")]
            "pl" => Ok(Self::Polish),
            #[cfg(feature = "polish")]
            "pol" => Ok(Self::Polish),
            #[cfg(feature = "polish")]
            "polish" => Ok(Self::Polish),
            #[cfg(feature = "portuguese")]
            "por" => Ok(Self::Portuguese),
            #[cfg(feature = "porter")]
            "porter" => Ok(Self::Porter),
            #[cfg(feature = "portuguese")]
            "portuguese" => Ok(Self::Portuguese),
            #[cfg(feature = "portuguese")]
            "pt" => Ok(Self::Portuguese),
            #[cfg(feature = "romanian")]
            "ro" => Ok(Self::Romanian),
            #[cfg(feature = "romanian")]
            "romanian" => Ok(Self::Romanian),
            #[cfg(feature = "romanian")]
            "ron" => Ok(Self::Romanian),
            #[cfg(feature = "russian")]
            "ru" => Ok(Self::Russian),
            #[cfg(feature = "romanian")]
            "rum" => Ok(Self::Romanian),
            #[cfg(feature = "russian")]
            "rus" => Ok(Self::Russian),
            #[cfg(feature = "russian")]
            "russian" => Ok(Self::Russian),
            #[cfg(feature = "serbian")]
            "serbian" => Ok(Self::Serbian),
            #[cfg(feature = "sesotho")]
            "sesotho" => Ok(Self::Sesotho),
            #[cfg(feature = "sesotho")]
            "sot" => Ok(Self::Sesotho),
            #[cfg(feature = "spanish")]
            "spa" => Ok(Self::Spanish),
            #[cfg(feature = "spanish")]
            "spanish" => Ok(Self::Spanish),
            #[cfg(feature = "serbian")]
            "sr" => Ok(Self::Serbian),
            #[cfg(feature = "serbian")]
            "srp" => Ok(Self::Serbian),
            #[cfg(feature = "sesotho")]
            "st" => Ok(Self::Sesotho),
            #[cfg(feature = "swedish")]
            "sv" => Ok(Self::Swedish),
            #[cfg(feature = "swedish")]
            "swe" => Ok(Self::Swedish),
            #[cfg(feature = "swedish")]
            "swedish" => Ok(Self::Swedish),
            #[cfg(feature = "tamil")]
            "ta" => Ok(Self::Tamil),
            #[cfg(feature = "tamil")]
            "tam" => Ok(Self::Tamil),
            #[cfg(feature = "tamil")]
            "tamil" => Ok(Self::Tamil),
            #[cfg(feature = "turkish")]
            "tr" => Ok(Self::Turkish),
            #[cfg(feature = "turkish")]
            "tur" => Ok(Self::Turkish),
            #[cfg(feature = "turkish")]
            "turkish" => Ok(Self::Turkish),
            #[cfg(feature = "yiddish")]
            "yi" => Ok(Self::Yiddish),
            #[cfg(feature = "yiddish")]
            "yid" => Ok(Self::Yiddish),
            #[cfg(feature = "yiddish")]
            "yiddish" => Ok(Self::Yiddish),
            _ => Err(crate::error::UnknownAlgorithm {
                name: key.to_string(),
            }),
        }
    }
}
