// @generated by scripts/sync_from_snowball.py — DO NOT EDIT

/// Git commit SHA of the snowball tree this crate was generated from.
pub const SNOWBALL_COMMIT: &str = "6772636350acfd63797e8cd24ff86c70fd2df6fc";

/// Committer date of [`SNOWBALL_COMMIT`] (`git log -1 --format=%cI`).
pub const SNOWBALL_COMMIT_TIME: &str = "2026-07-30T07:31:22+12:00";

/// `git describe` of the snowball tree at generation time.
pub const SNOWBALL_DESCRIBE: &str = "6772636";

/// Algorithm ids included in this generated tree (feature names).
pub const SNOWBALL_ALGORITHMS: &[&str] = &[
    "arabic",
    "armenian",
    "basque",
    "catalan",
    "czech",
    "danish",
    "dutch",
    "dutch_porter",
    "earlymodernenglish",
    "english",
    "esperanto",
    "estonian",
    "finnish",
    "french",
    "german",
    "greek",
    "hindi",
    "hungarian",
    "indonesian",
    "irish",
    "italian",
    "lithuanian",
    "lovins",
    "nepali",
    "norwegian",
    "persian",
    "polish",
    "porter",
    "portuguese",
    "romanian",
    "russian",
    "serbian",
    "sesotho",
    "spanish",
    "swedish",
    "tamil",
    "turkish",
    "yiddish",
];
