// @generated by scripts/sync_from_snowball.py — DO NOT EDIT

/// Full git commit SHA of the upstream snowball tree used to generate this crate.
///
/// This pin is the source of truth for which snowball revision the stemmed
/// algorithms correspond to. The crate **minor** version is derived from the
/// committer date of this commit (UTC `YYYYMMDD`).
///
/// See also [`SNOWBALL_COMMIT_TIME`] and [`SNOWBALL_DESCRIBE`].
pub const SNOWBALL_COMMIT: &str = "bc62b773b97749db7f5a804b632613ef34810046";

/// Committer timestamp of [`SNOWBALL_COMMIT`] (`git log -1 --format=%cI`).
///
/// The value is whatever git recorded (often with an offset); frostem converts
/// it to UTC when choosing the package **minor** version.
pub const SNOWBALL_COMMIT_TIME: &str = "2026-08-04T16:38:29+12:00";

/// `git describe --tags --always --dirty` of the snowball tree at generation time.
///
/// Useful for human-readable provenance when the tree is not exactly on a
/// release tag (typical while tracking `main`).
pub const SNOWBALL_DESCRIBE: &str = "bc62b77";

/// Canonical algorithm ids present in this generated tree.
///
/// These strings match Cargo feature names and [`crate::Algorithm::name`].
/// The list is independent of which features are enabled in a given build:
/// an id may appear here even if its feature was disabled by the consumer.
///
/// For algorithms actually compiled into the binary, use
/// [`crate::Algorithm::all`].
pub const SNOWBALL_ALGORITHMS: &[&str] = &[
    "arabic",
    "armenian",
    "basque",
    "catalan",
    "czech",
    "danish",
    "dutch",
    "dutch_porter",
    "earlymodernenglish",
    "english",
    "esperanto",
    "estonian",
    "finnish",
    "french",
    "german",
    "greek",
    "hindi",
    "hungarian",
    "indonesian",
    "irish",
    "italian",
    "lithuanian",
    "lovins",
    "nepali",
    "norwegian",
    "persian",
    "polish",
    "porter",
    "portuguese",
    "romanian",
    "russian",
    "serbian",
    "sesotho",
    "spanish",
    "swedish",
    "tamil",
    "turkish",
    "yiddish",
];
